# Get LinkedIn data

### Inputs: 
- `"../data/derived/linkedin_company_urls_final.csv"`

### Outputs:
- `"../data/derived/company_profiles.csv"`
  

### Purpose:

1. Add company profile data from Bright Data dataset.

In [1]:
import pandas as pd

In [2]:
companies = pd.read_csv("../data/derived/linkedin_company_urls_final.csv")
# companies = pd.read_csv("../data/derived/linkedin_company_urls_precheck.csv")

In [3]:
companies.columns

Index(['Company Name', 'LinkedIn URL'], dtype='object')

In [4]:
companies["LinkedIn URL"]

0           https://www.linkedin.com/company/verizon-labs
1                   https://in.linkedin.com/company/renew
2                   https://www.linkedin.com/company/citi
3               https://www.linkedin.com/company/epic1979
4          https://www.linkedin.com/company/dc-energy-llc
                              ...
3163      https://www.linkedin.com/company/wishforwheels/
3164         https://www.linkedin.com/company/wjpartners/
3165    https://www.linkedin.com/company/world-economi...
3166    https://www.linkedin.com/company/wynnchurch-ca...
3167            https://www.linkedin.com/company/youtube/
Name: LinkedIn URL, Length: 3168, dtype: object

In [5]:
# Bright Data download requies the LinkedIn URL slugs
import re


def get_slug(url: str) -> str | None:
    match = re.search(r"company/([^/\s]+)(?:/|$)", url)
    if match:
        return match.group(1)
    return None


slugs = companies["LinkedIn URL"].apply(get_slug)

In [6]:
slugs.to_csv("../data/derived/linkedin_company_slugs.csv", index=False, header=["id"])

Using the slugs, the [Bright Data LinkedIn dataset](https://brightdata.com/cp/datasets/browse/gd_l1vikfnt1wgvvqz95w?id=hl_0ba933c4) was filtered down to the available records:

In [7]:
bd_data = pd.read_csv("../data/bd_20250725_201305_0.csv")

In [8]:
companies = companies.set_index(slugs.rename("id"))

In [9]:
bd_data = bd_data.set_index("id")

In [10]:
companies = companies.merge(bd_data, on="id", how="left")

In [11]:
companies = companies.rename(columns={"LinkedIn URL": "scraped_linkedin_url"})
companies.columns = ["_".join(c.lower().split()) for c in companies.columns]
companies

,company_name,scraped_linkedin_url,name,country_code,locations,followers,employees_in_linkedin,about,specialties,company_size,...,stock_info,get_directions_url,description,additional_info,additional_information,country_codes_array,alumni,alumni_information,website_simplified,unformatted_about
id,,,,,,,,,,,,,,,,,,,,,
verizon-labs,Verizon Labs,https://www.linkedin.com/company/verizon-labs,Verizon Labs,NaN,[],5193.0,83.0,NaN,NaN,"10,001+ employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Verizon Labs | 5,193 followers on LinkedIn.",NaN,Additional jobs info: Network Operations Cente...,NaN,NaN,NaN,verizon.com,NaN
renew,ReNew Power,https://in.linkedin.com/company/renew,ReNew,IN,"[""Commercial Block, Zone 6, Golf Course Road D...",404759.0,4832.0,ReNew is a leading decarbonisation solutions p...,"Renewable Energy, Solar Energy , Wind Energy ,...","1,001-5,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","ReNew | 404,759 followers on LinkedIn. ReNew i...",NaN,"Additional jobs info: Graduate Engineer (29,65...","[""IN""]",NaN,NaN,renew.com,\n ReNew is a leading decarbonisa...
citi,Citibank,https://www.linkedin.com/company/citi,Citi,"US,CA,MY,PA,PE,MX,PH,HK,AE,GB,CO,IN,IL,TW","[""388 Greenwich Street New York, New York 1001...",4749962.0,195441.0,Citi's mission is to serve as a trusted partne...,"Banking, Commercial Banking, Investment Bankin...","10,001+ employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Citi | 4,749,962 followers on LinkedIn. Citi&#...",NaN,"Additional jobs info: Citi (9,127 open jobs). ...","[""US"",""CA"",""MY"",""PA"",""PE"",""MX"",""PH"",""HK"",""AE"",...",NaN,NaN,citigroup.com,\n Citi's mission is to serve as ...
epic1979,Epic Systems Corp,https://www.linkedin.com/company/epic1979,Epic,US,"[""1979 Milky Way Verona, WI 53593, US""]",878968.0,16306.0,Join us in our mission to help the world get w...,"healthcare, emr, ehr, phr, and software","10,001+ employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Epic | 878,968 followers on LinkedIn. ...with ...",NaN,NaN,"[""US""]",NaN,NaN,epic.com,\n Join us in our mission to help...
dc-energy-llc,DC Energy,https://www.linkedin.com/company/dc-energy-llc,DC Energy,US,"[""1600 Tysons Blvd Fifth Floor McLean, Virgini...",4220.0,106.0,DC Energy is a proprietary trading firm that f...,NaN,51-200 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","DC Energy | 4,220 followers on LinkedIn. DC En...",NaN,"Additional jobs info: Analyst (694,057 open jo...","[""US""]",NaN,NaN,dc-energy.com,\n DC Energy is a proprietary tra...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
wishforwheels,Wish for wheels,https://www.linkedin.com/company/wishforwheels/,Wish for Wheels,US,"[""4600 S Ulster St Suite 1050 Denver, Colorado...",2481.0,19.0,Wish for Wheels turns dreams into reality for ...,"Employee Engagement, Team Building, CSR, Corpo...",2-10 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Wish for Wheels | 2,481 followers on LinkedIn....",NaN,NaN,"[""US""]",NaN,NaN,wishforwheels.org,\n Wish for Wheels turns dreams i...
wjpartners,WJ Partners,https://www.linkedin.com/company/wjpartners/,WJ Partners,US,"[""100 E Dunbar St Spartanburg, South Carolina ...",538.0,12.0,Built on the foundation of a long history of p...,NaN,2-10 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...",WJ Partners | 538 followers on LinkedIn. Build...,NaN,"Additional jobs info: Analyst (694,057 open jo...","[""US""]",NaN,NaN,wjpartners.com,\n Built on the foundation of a l...
world-economic-forum,World Economic Forum/Yunus Social Business,https://www.linkedin.com/company/world-economi...,World Economic Forum,"CH,US,CN,JP","[""91-93, Route de la Capite Cologny, Geneva CH...",5435781.0,5192.0,We are the international institution for publi...,NaN,"501-1,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","World Economic Forum | 5,435,781 followers on ...",NaN,Additional jobs info: World Economic Forum (51...,"[""CH"",""US"",""CN"",""JP""]",NaN,NaN,weforum.org,\n We are the international insti...
wynnchurch-capital,Wynnchurch Capital,https://www.linkedin.com/company/wynnchurch-ca...,"Wynnchurch Capital, L.P.",US,"[""6250 N. River Road Suite 10-100 Rosemont, Il...",10721.0,61.0,"Wynnchurch Capital, L.P., headquartered in the...","Expedient and discreet diligence process, Cert...",11-50 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Wynnchurch Capital, L.P. | 10,721 followers on...",NaN,"Additional jobs info: Analyst (694,057 open jo...","[""US""]",NaN,NaN,wynnchurch.com,"\n Wynnchurch Capital, L.P., head..."
youtube,YouTube LLC,https://www.linkedin.com/company/youtube/,YouTube,US,"[""901 Cherry Ave. San Bruno, CA 94066, US""]",2278904.0,129988.0,"YouTube is a team-oriented, creative workplace...",NaN,"1,001-5,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","YouTube | 2,278,904 followers on LinkedIn. Lik...",NaN,NaN,"[""US""]",NaN,NaN,youtube.com,"\n YouTube is a team-oriented, cr..."

In [12]:
companies.to_csv("../data/derived/company_profiles.csv")

## Determine the impact of missing companies

Let's determine how many samples we lose due to lack of company data.

In [13]:
admissions_data = pd.read_csv("../data/derived/admissions.csv")

records = pd.Series(
    admissions_data["Job 1 Organization"].tolist(),
    name="Company",
)

record_count = records.value_counts().reset_index()

In [20]:
missing_companies = companies[companies.industries.isna()]

In [21]:
record_count[record_count["Company"].isin(missing_companies.company_name)].merge(
    missing_companies[["company_name", "scraped_linkedin_url"]],
    left_on="Company",
    right_on="company_name",
    how="left",
).drop(columns="company_name")

,Company,count,scraped_linkedin_url
0,athenahealth,4,https://in.linkedin.com/company/athenahealth-t...
1,Goldman Sachs,3,https://it.linkedin.com/company/goldmansachspfm
2,Swiggy,2,https://www.linkedin.com/company/swiggy
3,Discover Financial Services,2,https://cn.linkedin.com/company/discover-finan...
4,FactSet Research Systems,2,https://www.linkedin.com/company/factset-resea...
...,...,...,...
91,Amandla Charter School,1,https://www.linkedin.com/company/amandla-chart...
92,Virtuali Inc.,1,https://ar.linkedin.com/company/virtuali-inc-
93,Glencore International AG,1,https://www.linkedin.com/company/xstrata-nickel
94,Independent Consulting,1,https://www.linkedin.com/company/independent-c...
95,Up2Us Sports,1,https://na.linkedin.com/company/up2ussports