# Get LinkedIn data

### Inputs: 
- `"../data/derived/linkedin_company_urls_final.csv"`

### Outputs:
- `"../data/derived/company_profiles.csv"`
  

### Purpose:

1. Add company profile data from Bright Data dataset.

In [2]:
import pandas as pd

In [3]:
# companies = pd.read_csv("../data/derived/linkedin_company_urls_final.csv")
companies = pd.read_csv("../data/derived/linkedin_company_urls_precheck.csv")

In [4]:
companies.columns

Index(['Company Name', 'LinkedIn URL', 'Reasoning', 'Is Valid',
       'Validated URL'],
      dtype='object')

In [7]:
companies["LinkedIn URL"]

0           https://www.linkedin.com/company/verizon-labs
1                   https://in.linkedin.com/company/renew
2                   https://www.linkedin.com/company/citi
3               https://www.linkedin.com/company/epic1979
4          https://www.linkedin.com/company/dc-energy-llc
                              ...
2983    https://www.linkedin.com/company/university-of...
2984    https://www.linkedin.com/company/standardchart...
2985    https://www.linkedin.com/company/impact-hub-bo...
2986            https://www.linkedin.com/company/rapidsos
2987    https://www.linkedin.com/company/stepstone-group/
Name: LinkedIn URL, Length: 2988, dtype: object

In [8]:
# Bright Data download requies the LinkedIn URL slugs
import re


def get_slug(url: str) -> str | None:
    match = re.search(r"company/([^/\s]+)(?:/|$)", url)
    if match:
        return match.group(1)
    return None


slugs = companies["LinkedIn URL"].apply(get_slug)

In [9]:
slugs.to_csv("../data/derived/linkedin_company_slugs.csv", index=None, header=["id"])

Using the slugs, the [Bright Data LinkedIn dataset](https://brightdata.com/cp/datasets/browse/gd_l1vikfnt1wgvvqz95w?id=hl_0ba933c4) was filtered down to the available records:

In [8]:
bd_data = pd.read_csv("../data/bd_20250422_150813_0.csv")

In [9]:
companies = companies.set_index(slugs.rename("id"))

In [10]:
bd_data = bd_data.set_index("id")

In [11]:
companies = companies.merge(bd_data, on="id", how="left")

In [12]:
companies = companies.rename(columns={"LinkedIn URL": "scraped_linkedin_url"})
companies.columns = ["_".join(c.lower().split()) for c in companies.columns]
companies

,company_name,scraped_linkedin_url,name,country_code,locations,followers,employees_in_linkedin,about,specialties,company_size,...,stock_info,get_directions_url,description,additional_info,additional_information,country_codes_array,alumni,alumni_information,website_simplified,unformatted_about
id,,,,,,,,,,,,,,,,,,,,,
verizon-labs,Verizon Labs,https://www.linkedin.com/company/verizon-labs,Verizon Labs,NaN,[],5157.0,84.0,NaN,NaN,"10,001+ employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Verizon Labs | 5,157 followers on LinkedIn.",NaN,Additional jobs info: Network Operations Cente...,NaN,NaN,NaN,verizon.com,NaN
renew,ReNew Power,https://in.linkedin.com/company/renew,ReNew,IN,"[""Commercial Block, Zone 6, Golf Course Road D...",376890.0,4555.0,ReNew is a leading decarbonisation solutions p...,"Renewable Energy, Solar Energy , Wind Energy ,...","1,001-5,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","ReNew | 376,890 followers on LinkedIn. ReNew i...",NaN,"Additional jobs info: Graduate Engineer (29,65...","[""IN""]",NaN,NaN,renew.com,\n ReNew is a leading decarbonisa...
citi,Citibank,https://www.linkedin.com/company/citi,Citi,"US,CA,MY,PA,PE,MX,PH,HK,AE,GB,CO,IN,IL,TW","[""388 Greenwich Street New York, New York 1001...",4604840.0,193802.0,Citi's mission is to serve as a trusted partne...,"Banking, Commercial Banking, Investment Bankin...","10,001+ employees",...,"{""datetime"":""April 21, 2025"",""id"":""C"",""stock_e...","[{""directions_url"":""https://www.bing.com/maps?...","Citi | 4,604,840 followers on LinkedIn. Citi&#...",NaN,"Additional jobs info: Citi (1,410 open jobs). ...","[""US"",""CA"",""MY"",""PA"",""PE"",""MX"",""PH"",""HK"",""AE"",...",NaN,NaN,citigroup.com,\n Citi's mission is to serve as ...
epic1979,Epic Systems Corp,https://www.linkedin.com/company/epic1979,Epic,US,"[""1979 Milky Way Verona, WI 53593, US""]",831666.0,15723.0,Join us in our mission to help the world get w...,"healthcare, emr, ehr, phr, and software","10,001+ employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Epic | 831,666 followers on LinkedIn. ...with ...",NaN,"Additional jobs info: Epic (49,985 open jobs)....","[""US""]",NaN,NaN,epic.com,\n Join us in our mission to help...
dc-energy-llc,DC Energy,https://www.linkedin.com/company/dc-energy-llc,DC Energy,US,"[""1600 Tysons Blvd Fifth Floor McLean, Virgini...",4109.0,105.0,DC Energy is a proprietary trading firm that f...,NaN,51-200 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","DC Energy | 4,109 followers on LinkedIn. DC En...",NaN,"Additional jobs info: Analyst (36,938 open job...","[""US""]",NaN,NaN,dc-energy.com,\n DC Energy is a proprietary tra...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
yahoo-finance,Yahoo Inc.,https://www.linkedin.com/company/yahoo-finance,Yahoo Finance,US,"[""770 Broadway New York, 10003, US""]",122042.0,546.0,"Yahoo Finance provides free stock quotes, up-t...",NaN,51-200 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Yahoo Finance | 122,042 followers on LinkedIn....",NaN,NaN,"[""US""]",NaN,NaN,yhoo.it,\n Yahoo Finance provides free st...
yaleonline,Yale University,https://www.linkedin.com/company/yaleonline,Yale Online,US,"[""301 York St New Haven, Connecticut 06511, US""]",6085.0,1.0,"This is Yale, online. Since its founding in 17...","Education, E-Learning, Mobile Learning, Workpl...",51-200 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Yale Online | 6,085 followers on LinkedIn. Exp...",NaN,"Additional jobs info: Journalist (1,540 open j...","[""US""]",NaN,NaN,online.yale.edu,NaN
yum-brands,"Yum China Holding, Inc.",https://www.linkedin.com/company/yum-brands,Yum! Brands,US,"[""1441 Gardiner Lane Louisville, KY 40213, US""]",279682.0,7100.0,"Yum! Brands, Inc., based in Louisville, Kentuc...","Quick service restaurants, chicken, pizza, tac...","1,001-5,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Yum! Brands | 279,682 followers on LinkedIn. B...",NaN,NaN,"[""US""]",NaN,NaN,yum.com,"\n Yum! Brands, Inc., based in Lo..."
zero-space-usa-inc,"ZeroTurnaround USA, Inc.",https://www.linkedin.com/company/zero-space-us...,Zero Space USA Inc.,US,"[""6255 Providence Way Eastvale, California 928...",14.0,5.0,"Zero Space USA Inc, supported by Tsinghua Tong...",NaN,11-50 employees,...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...",Zero Space USA Inc. | 14 followers on LinkedIn...,NaN,NaN,"[""US""]",NaN,NaN,zerospaceusa.com,NaN
zillow,Zillow Group,https://www.linkedin.com/company/zillow/jobs,Zillow,US,"[""Seattle, Washington, US""]",447752.0,9069.0,Join our mission to give the people power to u...,"Real Estate, Home Values, Mortgages, Homes for...","5,001-10,000 employees",...,NaN,"[{""directions_url"":""https://www.bing.com/maps?...","Zillow | 447,752 followers on LinkedIn. Reimag...",NaN,NaN,"[""US""]",NaN,NaN,zillow.com,\n Join our mission to give the p...

In [13]:
companies.to_csv("../data/derived/company_profiles.csv")

## Determine the impact of missing companies

Let's determine how many samples we lose due to lack of company data.

In [14]:
admissions_data = pd.read_csv("../data/derived/admissions.csv")

records = pd.Series(
    admissions_data["Job 1 Organization"].tolist(),
    name="Company",
)

record_count = records.value_counts().reset_index()

In [15]:
missing_companies = companies[companies.company_id.isna()]

In [22]:
record_count[record_count["Company"].isin(missing_companies.company_name)].merge(
    missing_companies[["company_name", "scraped_linkedin_url"]],
    left_on="Company",
    right_on="company_name",
    how="left",
).drop(columns="company_name")

,Company,count,scraped_linkedin_url
0,Goldman Sachs,3,https://it.linkedin.com/company/goldmansachspfm
1,Capital One Financial Corporation,1,https://es.linkedin.com/company/capital-one-fi...
2,CJ O Shopping,1,https://in.linkedin.com/company/a-cj-o-shoppin...
3,Duzce Municipality,1,https://www.linkedin.com/company/d%C3%BCzce-be...
4,Nestle Central & West Africa,1,https://af.linkedin.com/company/nestle-central...
5,Interdisciplinary Institute of Political Economy,1,https://www.linkedin.com/company/institute-of-...
6,Trinity Partners,1,https://www.linkedin.com/company/trinity-partn...
7,Impendi Analytics,1,https://rs.linkedin.com/company/impendi
8,Mason Square Capital,1,https://fr.linkedin.com/company/mason-square-c...
9,MaxPoint Interactive,1,https://ie.linkedin.com/company/maxpoint
10,UBS AG,1,https://be.linkedin.com/company/united-beet-seeds
11,Chevron Corporation,1,https://ph.linkedin.com/company/chevron-holdin...
12,SQZ Biotechnologies Company,1,https://na.linkedin.com/company/sqz-biotechnol...
13,Adviser Investments,1,https://na.linkedin.com/company/adviser-invest...
14,Salient Partners,1,https://in.linkedin.com/company/salientpartners
15,Edelweiss Capital,1,https://www.linkedin.com/company/edelweisscapital
16,Deloitte&Touche Financial Advisory Services Li...,1,https://www.linkedin.com/company/deloitte-tohm...
17,Forward Management (acquired by Salient Partners),1,https://in.linkedin.com/company/salientpartners
18,Kairos Aerospace,1,https://at.linkedin.com/company/kairosaerospace/
19,Blue Moon Digital,1,https://ae.linkedin.com/company/blue-moon-digi...
20,"Brand Networks, LLC",1,https://mx.linkedin.com/company/brandnetworks
21,Werfen,1,https://it.linkedin.com/company/werfen-oem
22,"Grant Thornton, LLP",1,https://tt.linkedin.com/company/grant-thornton...
23,MBL International Corporation,1,https://tt.linkedin.com/company/mbl-international
24,Diario Altavoz,1,https://www.linkedin.com/company/diario-altavoz
25,E.I. duPont de Nemours and Company,1,https://gp.linkedin.com/company/e.i.-du-pont-d...
26,Alaska Airmen Association,1,https://www.linkedin.com/company/alaska-airmen...
27,Bully Pulpit Interactive,1,https://na.linkedin.com/company/bully-pulpit-i...
28,Ernst & Young GmbH,1,https://www.linkedin.com/company/ernst-&-young...
29,Deloitte Anijn LLC,1,https://kr.linkedin.com/company/%EB%94%9C%EB%A...
30,Project Genetics,1,https://nz.linkedin.com/company/project-genetics
31,Burke Mountain Academy,1,https://ca.linkedin.com/company/burkemountain
32,"Trinity Partners, Life Sciences Consulting Firm",1,https://www.linkedin.com/company/trinity-partn...
33,"Goldman, Sachs & Co.",1,https://et.linkedin.com/company/goldman-sachs-...
34,Up2Us Sports,1,https://na.linkedin.com/company/up2ussports
35,Virtuali Inc.,1,https://ar.linkedin.com/company/virtuali-inc-