# Supplemental Gender Data

In previous work, manual industry classifications were made for a smaller dataset. We can leverage these categories in addition to the US Census categories.

In fact, these categories should be preferred because the corresponding percentages were researched to be representative of the actual industry.

This notebook generates a JSON file with those industry categories and the corresponding percentages.

In [14]:
import pandas as pd

In [15]:
df = pd.read_excel("../data/supplemental/data_table_forsimon-jm.xlsx", na_values=["."])

In [19]:
df.loc[df.indus == "Healthcare", ["indus_coded", "indus_gen_percentage"]]

                            indus_coded  indus_gen_percentage
167          Health, Wellness & Fitness                  69.9
169                    Higher Education                  67.1
170                            Research                  71.6
171                    Higher Education                  67.1
699                      Medical Device                  39.4
700                      Medical Device                  39.4
701                      Medical Device                  39.4
709              Hospital & Health Care                  74.9
710                    Medical Practice                  39.4
1107  Information Technology & Services                  32.0
1108  Information Technology & Services                  32.0
1109  Information Technology & Services                  32.0
1110  Information Technology & Services                  32.0
1556                          Insurance                  54.7

In [9]:
df.loc[df.indus.isna(), ["indus", "indus_coded", "indus_gen_percentage"]]

     indus             indus_coded  indus_gen_percentage
933    NaN                     NaN                   NaN
1588   NaN  Hospital & Health Care                  32.0
1830   NaN                     NaN                   NaN
1831   NaN                     NaN                   NaN
1832   NaN                     NaN                   NaN
1833   NaN                     NaN                   NaN
1834   NaN                     NaN                   NaN
1835   NaN                     NaN                   NaN
1836   NaN                     NaN                   NaN
1837   NaN                     NaN                   NaN

In [10]:
df = df.dropna(subset=["indus", "indus_gen_percentage"])

In [11]:
df[["indus", "indus_gen_percentage"]].drop_duplicates().to_csv(
    "../data/supplemental/industry_female_percentages.csv", index=False
)