In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("../data/supplemental/data_table_forsimon.xlsx")

In [12]:
df[df.indus_coded == "."]

,jhid,matric_yr,birthdate,matric_age,gender,marital_gsb,marry_gsb,single_gsb,kids_gsb,marital_2021,...,und_gradyr,other_educ,conc_gsb,conc_entered,numconc,clubs,cohort,prior_workexp_gsb,gpa,gpa_missing
11,4,2008,1981-03-18,25.50,F,Single,0,1,0,1,...,2003,"University of Chicago: Certificate, Health Adm...","Entrepreneurship,Marketing Management","Finance, Entrepreneurship",2,"Chicago Women in Business, Entrepreneur/VC Gro...",Harper 2006,39.0,3.333,0
20,33,2008,1980-11-09,25.83,F,Single,0,1,0,.,...,2003,.,Finance,"Finance, Accounting",2,"Chicago Women in Business, Giving Something Ba...",Walker 2006,36.0,2.768,0
61,78,2008,1980-12-10,25.75,F,Single,0,1,0,.,...,2003,.,"Economics,Entrepreneurship,Finance,Marketing M...","Finance, Economics, Entrepreneurship",3,"Chicago Business, Graduate Business Council, H...",Stuart 2006,36.0,3.092,0
82,92,2008,1971-12-27,34.75,F,Single,0,1,0,1,...,1993,"MS - Industrial Engineering; (1994-97), Stanfo...","General Management,Managerial & Organizational...","General Management, Managerial & Organizationa...",4,"African American MBA Association, Chicago Wome...",Nobels 2006,110.0,3.579,0
132,131,2008,1979-06-21,27.25,F,Married,1,0,0,1,...,2001,The Coaches Training Institute; Moksha Yoga Ce...,"Entrepreneurship,Marketing Management","Managerial & Organizational Behavior, Entrepre...",3,"Corporate Management and Strategy Group, GSB M...",Maroons 2006,62.0,3.699,0
134,131,2008,1979-06-21,27.25,F,Married,1,0,0,1,...,2001,The Coaches Training Institute; Moksha Yoga Ce...,"Entrepreneurship,Marketing Management","Managerial & Organizational Behavior, Entrepre...",3,"Corporate Management and Strategy Group, GSB M...",Maroons 2006,62.0,3.699,0
135,131,2008,1979-06-21,27.25,F,Married,1,0,0,1,...,2001,The Coaches Training Institute; Moksha Yoga Ce...,"Entrepreneurship,Marketing Management","Managerial & Organizational Behavior, Entrepre...",3,"Corporate Management and Strategy Group, GSB M...",Maroons 2006,62.0,3.699,0
138,131,2008,1979-06-21,27.25,F,Married,1,0,0,1,...,2001,The Coaches Training Institute; Moksha Yoga Ce...,"Entrepreneurship,Marketing Management","Managerial & Organizational Behavior, Entrepre...",3,"Corporate Management and Strategy Group, GSB M...",Maroons 2006,62.0,3.699,0
163,174,2008,1981-02-27,25.58,F,Single,0,1,0,.,...,2002,Certificate in Entrepreneurship and New Ventur...,Entrepreneurship,"Entrepreneurship, Strategic Management",2,"Class Agent, Cohort Class Agent, Admissions Gr...",Harper 2006,51.0,3.039,0
212,235,2008,1981-11-03,24.83,F,Single,0,1,0,.,...,2004,University of Melbourne - Bachelor of Laws wit...,"Entrepreneurship,International Business,Strate...","Finance, Strategic Management, Entrepreneurship",3,"Cohort Social Rep, Middle East & North Africa ...",NaN,NaN,2.84,0
238,291,2008,1978-07-13,28.17,F,Single,0,1,0,.,...,2000,"Johns Hopkins, MA - Foreign Affairs, 2001","Finance,International Business","Entrepreneurship, Accounting, Finance",3,Investment Banking Group,NaN,NaN,3.088,0
426,510,2008,1978-12-19,27.75,F,Single,0,1,0,1,...,2000,.,NaN,"Marketing Management, Entrepreneurship, Strate...",3,"Management Consulting Group, Booth Golf Club, ...",NaN,NaN,3.58,0
729,894,2008,1978-02-10,28.58,F,Single,0,1,0,1,...,1999,Stanford University - MS - Computer Science - ...,NaN,"Strategic Management, Marketing Management, Fi...",3,"European Business Group, Entrepreneur/VC Group...",NaN,NaN,3.549,0
731,894,2008,1978-02-10,28.58,F,Single,0,1,0,1,...,1999,Stanford University - MS - Computer Science - ...,NaN,"Strategic Management, Marketing Management, Fi...",3,"European Business Group, Entrepreneur/VC Group...",NaN,NaN,3.549,0
829,2257,2008,1980-01-15,26.67,F,Married,1,0,0,.,...,2002,.,NaN,Entrepreneurship,3,.,NaN,NaN,3.211,0
909,2610,2009,1976-07-18,31.17,F,Single,0,1,0,.,...,1997,.,NaN,Managerial & Organizational Behavior; Strategi...,3,Leadership & Outdoors Group; Business Solution...,NaN,NaN,3.429,0
929,2614,2009,1979-01-04,28.67,F,Single,0,1,0,.,...,2000,.,NaN,Managerial & Organizational Behavior; Marketi...,3,Chicago Women in Business (Leader); Class Agen...,NaN,NaN,3.237,0
933,2614,2009,1979-01-04,28.67,F,Single,0,1,0,.,...,2000,.,NaN,Managerial & Organizational Behavior; Marketi...,3,Chicago Women in Business (Leader); Class Agen...,NaN,NaN,3.237,0
1162,2826,2009,1980-09-14,27.00,F,Single,0,1,0,.,...,2002,.,NaN,Strategic Management; Finance; Marketing Manag...,3,Management Consulting Group; Entrepreneur/VC G...,NaN,NaN,3.801,0
1226,2879,2009,1981-11-15,25.83,F,Single,0,1,0,.,...,2003,.,NaN,"Finance, Accounting, Entrepreneurship",3,Greater China Club (Leader),NaN,NaN,3.459,0
1356,2985,2009,1974-04-25,33.42,F,Married,1,0,0,.,...,1997,Virginia Polytechnic Institute & State Univers...,NaN,Finance; Entrepreneurship,3,Graduate with Honors; Operations Management Gr...,NaN,NaN,3.859,0
1408,3063,2009,1982-06-14,25.25,F,Single,0,1,0,1,...,2004,.,NaN,Economics; Entrepreneurship; Finance,3,Corporate Management & Strategy Group; Managem...,NaN,NaN,3.397,0
1511,3166,2009,1978-01-21,29.67,F,Single,0,1,0,.,...,1999,.,NaN,Strategic Management; Finance; Entrepreneurship,3,.,NaN,NaN,.,1
1595,3249,2009,1977-07-07,30.17,F,Single,0,1,0,.,...,1999,Purdue University - Masters - Engineering Mana...,NaN,"Economics, Marketing Management, Strategic Man...",3,.,NaN,NaN,3.619,0
1744,3411,2009,1982-03-20,25.50,F,Single,0,1,0,.,...,2004,.,NaN,Marketing Management; Strategic Management,2,.,NaN,NaN,.,1
1802,3469,2009,1981-01-27,26.67,F,Single,0,1,0,.,...,2002,.,NaN,.,3,Chicago Asia Pacific Group (Co-Chair),NaN,NaN,.,1
1828,3499,2009,1977-08-31,30.08,F,Single,0,1,0,.,...,1999,"Master of Science (MS) - Accounting & Finance,...",NaN,"Marketing Management, Strategic Management, En...",3,.,NaN,NaN,.,1

In [10]:
df[["indus", "indus_gen_percentage"]].drop_duplicates()

                                     indus indus_gen_percentage
0                              Hospitality                 51.2
4     Healthcare Consulting: Senior Living                 69.9
5               Entertainment/Movie Rental                   46
11                 NO RECORD OF EMPLOYMENT                    .
12                   Management Consulting                   32
...                                    ...                  ...
1779           Primary/Secondary Education                 68.1
1781                               Banking                  1.9
1784                         Entertainment                 32.7
1802                     Glass/Environment                 26.7
1829                            Non-Profit                    .

[378 rows x 2 columns]